import {
  AlertTriangle,
  Bell,
  Building2,
  CalendarDays,
  CheckSquare,
  ClipboardList,
  CreditCard,
  Database,
  FileText,
  Files,
  FolderKanban,
  HardHat,
  HelpCircle,
  Home,
  Link2,
  ScrollText,
  Settings,
  Shield,
  Tags,
  Truck,
  Upload,
  Users,
  Wallet,
  Banknote,
  BarChart3,
} from "lucide-react";

const map: Record<string, typeof Home> = {
  home: Home,
  building: Building2,
  folder: FolderKanban,
  hardhat: HardHat,
  users: Users,
  link: Link2,
  truck: Truck,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  wallet: Wallet,
  banknote: Banknote,
  filetext: FileText,
  creditcard: CreditCard,
  tags: Tags,
  files: Files,
  alert: AlertTriangle,
  check: CheckSquare,
  chart: BarChart3,
  scroll: ScrollText,
  shield: Shield,
  upload: Upload,
  database: Database,
  settings: Settings,
  bell: Bell,
  help: HelpCircle,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = map[name] ?? FileText;
  return <Icon className={className} size={16} strokeWidth={1.75} />;
}
